abs.o: main.o play.o barracks.o
	g++ -std=c++11 -o abs.o main.o play.o barracks.o

main.o : main.cpp
	g++ -std=c++11 -c -o main.o main.cpp

play.o : play.cpp
	g++ -std=c++11 -c -o play.o play.cpp

barracks.o : barracks.cpp
	g++ -std=c++11 -c -o barracks.o barracks.cpp
